export const mapStyle = [
    {
        featureType: '',
        elementType: 'geometry.stroke',
        stylers: [
            {
                hue: null,
                lightness: null,
                saturation: null,
                gamma: null,
                invertLightness: null,
                visibility: null,
                color: '#d7dedf',
                weight: null,
                textScale: null,
                zoom: null,
            },
            {
                hue: null,
                lightness: null,
                saturation: null,
                gamma: null,
                invertLightness: null,
                visibility: 'on',
                color: null,
                weight: null,
                textScale: null,
                zoom: null,
            },
        ],
    },
    {
        featureType: '',
        elementType: 'labels',
        stylers: [
            {
                hue: null,
                lightness: null,
                saturation: null,
                gamma: null,
                invertLightness: null,
                visibility: 'off',
                color: null,
                weight: null,
                textScale: null,
                zoom: null,
            },
        ],
    },
    {
        featureType: 'administrative',
        elementType: 'geometry.stroke',
        stylers: [
            {
                hue: null,
                lightness: null,
                saturation: null,
                gamma: null,
                invertLightness: null,
                visibility: null,
                color: '#d7dedf',
                weight: null,
                textScale: null,
                zoom: null,
            },
            {
                hue: null,
                lightness: null,
                saturation: null,
                gamma: null,
                invertLightness: null,
                visibility: 'on',
                color: null,
                weight: null,
                textScale: null,
                zoom: null,
            },
            {
                hue: null,
                lightness: null,
                saturation: null,
                gamma: null,
                invertLightness: null,
                visibility: null,
                color: null,
                weight: 1,
                textScale: null,
                zoom: null,
            },
        ],
    },
    {
        featureType: 'administrative.land_parcel',
        elementType: 'geometry.stroke',
        stylers: [
            {
                hue: null,
                lightness: null,
                saturation: null,
                gamma: null,
                invertLightness: null,
                visibility: 'on',
                color: null,
                weight: null,
                textScale: null,
                zoom: null,
            },
        ],
    },
    {
        featureType: 'administrative.locality',
        elementType: 'labels.text',
        stylers: [
            {
                visibility: 'simplified',
            },
        ],
    },
    {
        featureType: 'landscape.man_made',
        elementType: '',
        stylers: [
            {
                hue: null,
                lightness: null,
                saturation: null,
                gamma: null,
                invertLightness: null,
                visibility: 'off',
                color: null,
                weight: null,
                textScale: null,
                zoom: null,
            },
        ],
    },
    {
        featureType: 'landscape.natural',
        elementType: '',
        stylers: [
            {
                hue: null,
                lightness: null,
                saturation: null,
                gamma: null,
                invertLightness: null,
                visibility: null,
                color: '#ffffff',
                weight: null,
                textScale: null,
                zoom: null,
            },
            {
                hue: null,
                lightness: null,
                saturation: null,
                gamma: null,
                invertLightness: null,
                visibility: 'on',
                color: null,
                weight: null,
                textScale: null,
                zoom: null,
            },
        ],
    },
    {
        featureType: 'poi',
        elementType: '',
        stylers: [
            {
                hue: null,
                lightness: null,
                saturation: null,
                gamma: null,
                invertLightness: null,
                visibility: 'off',
                color: null,
                weight: null,
                textScale: null,
                zoom: null,
            },
        ],
    },
    {
        featureType: 'poi.park',
        elementType: '',
        stylers: [
            {
                hue: null,
                lightness: null,
                saturation: null,
                gamma: null,
                invertLightness: null,
                visibility: 'off',
                color: null,
                weight: null,
                textScale: null,
                zoom: null,
            },
        ],
    },
    {
        featureType: 'road',
        elementType: 'geometry.fill',
        stylers: [
            {
                hue: null,
                lightness: null,
                saturation: null,
                gamma: null,
                invertLightness: null,
                visibility: 'off',
                color: null,
                weight: null,
                textScale: null,
                zoom: null,
            },
        ],
    },
    {
        featureType: 'transit',
        elementType: '',
        stylers: [
            {
                hue: null,
                lightness: null,
                saturation: null,
                gamma: null,
                invertLightness: null,
                visibility: 'off',
                color: null,
                weight: null,
                textScale: null,
                zoom: null,
            },
        ],
    },
    {
        featureType: 'water',
        elementType: '',
        stylers: [
            {
                hue: null,
                lightness: null,
                saturation: null,
                gamma: null,
                invertLightness: null,
                visibility: null,
                color: '#d7dedf',
                weight: null,
                textScale: null,
                zoom: null,
            },
            {
                hue: null,
                lightness: null,
                saturation: null,
                gamma: null,
                invertLightness: null,
                visibility: 'on',
                color: null,
                weight: null,
                textScale: null,
                zoom: null,
            },
        ],
    },
]
export default mapStyle
